7.6. Вход на сайт
htmlacademy-php/51061-readme-12 pull request #16
Opened 2022-05-18 13:37 UTC by gladk0ff

2022-05-22 19:09 UTC, ademaro commented on authentication.php
> +<?php
хм, какой смысл у этого файла?

2022-05-22 19:11 UTC, ademaro commented on feed.php
> +require_once('authentication.php');
ах вот зачем) но у тебя же уже есть $is_auth, используй сразу тут проверку, например. Если нет доступа — желательно не просто редирект, а, может, 403? отдельный файл — очень сомнительно для одной проверки. Явное лучше чем неявное, давай подумаем как сделать лучше

2022-05-22 19:12 UTC, ademaro commented on feed.php
> +    'feed.php'
а мы разве не должны данные в этот шаблон какие-то передать?)

2022-05-22 19:12 UTC, ademaro commented on feed.php
> +?>
убираем эту строчку

2022-05-22 19:13 UTC, ademaro commented on helpers/helpers.php
> +        mysqli_stmt_bind_param(...$values);
отлично!

2022-05-22 19:14 UTC, ademaro commented on index.php
> +if (isset($_SESSION['user'])) {
давай уж дальше дорефакторим

2022-05-22 19:15 UTC, ademaro commented on index.php
> +</head>
в контроллере разметка появилась?

2022-05-22 19:16 UTC, ademaro commented on templates/layout.php
> +$current_url = $_SERVER['REQUEST_URI'];
зачем это в шаблоне?

2022-05-22 19:17 UTC, ademaro requested changes
давай сделаем поправки всё-таки, что бы спокойно двинуть дальше

2022-05-26 19:38 UTC, gladk0ff commented on authentication.php
> +<?php
уберу)

2022-05-26 19:41 UTC, gladk0ff commented on feed.php
> +require_once('authentication.php');
согласен через is_auth логичней) 
 Если нет доступа — желательно не просто редирект, а, может, 403?  - начет этого не соглашусь 
- по тз если не зарегестрирован то на вход) да и 403 наверно больше подойдет если на проекте ролевки разные и у этой роли нет доступа к такому то подразделу раздела) то да

2022-05-26 19:42 UTC, gladk0ff commented on feed.php
> +    'feed.php'
на данном этапе по усмотрению  - я его решил постепенно наращивать)

2022-05-26 19:43 UTC, gladk0ff commented on index.php
> +if (isset($_SESSION['user'])) {
заменил на $is_auth если ты об этом)

2022-05-27 17:13 UTC, gladk0ff commented on index.php
> +</head>
так было по задание мол тупой шаблон) но я Тебя услышал)

2022-05-27 17:14 UTC, gladk0ff commented on templates/layout.php
> +$current_url = $_SERVER['REQUEST_URI'];
для отображения выделенного меню) но тож убрал

2022-05-29 07:10 UTC, ademaro commented on templates/sign-in.php
> +<!DOCTYPE html>
а наследовать один базовый шаблон можем?) DRY даже в шаблонах было бы круто реализовать)

2022-05-29 07:10 UTC, ademaro approved these changes

2022-05-29 07:10 UTC, merged